-- OBSOLETO: el esquema en PostgreSQL (producción / Render) lo gestiona Flyway en db/migration/.
-- El perfil local `dev` usa H2 con Hibernate ddl-auto=update y spring.sql.init.mode=never,
-- por lo que este fichero no se ejecuta. Mantener solo como referencia histórica.
